import os
import joblib
import streamlit as st

# ---------- Path resolution (works in root OR /src) ----------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Try common locations:
# 1) models/ next to app file
# 2) models/ one level above (if app is in /src)
CANDIDATE_MODEL_PATHS = [
    os.path.join(BASE_DIR, "models", "sentiment_model.joblib"),
    os.path.join(BASE_DIR, "..", "models", "sentiment_model.joblib"),
]

CANDIDATE_REPORT_PATHS = [
    os.path.join(BASE_DIR, "models", "training_report.md"),
    os.path.join(BASE_DIR, "..", "models", "training_report.md"),
]

def first_existing_path(paths: list[str]) -> str:
    for p in paths:
        if os.path.exists(p):
            return p
    # default to first candidate for nicer error messages
    return paths[0]

MODEL_PATH = first_existing_path(CANDIDATE_MODEL_PATHS)
REPORT_PATH = first_existing_path(CANDIDATE_REPORT_PATHS)

# ---------- Helpers ----------
def file_ready(path: str) -> bool:
    """File must exist and be non-empty (guards against 0-byte placeholders)."""
    return os.path.exists(path) and os.path.getsize(path) > 0

@st.cache_resource(show_spinner=False)
def load_model_cached(path: str):
    """Load model + vectorizer once per app session."""
    return joblib.load(path)  # returns (vectorizer, model)

def render_model_not_ready():
    st.error(
        "Model file is missing or empty.\n\n"
        "This app expects `models/sentiment_model.joblib` to be generated by the GitHub Actions training pipeline "
        "and committed back into the repository."
    )

    st.markdown("### Debug info (for troubleshooting)")
    st.code(
        "\n".join([
            f"cwd: {os.getcwd()}",
            f"app file: {__file__}",
            f"BASE_DIR: {BASE_DIR}",
            "candidate model paths:",
            *[f"  - {p} (exists={os.path.exists(p)})" for p in CANDIDATE_MODEL_PATHS],
            "candidate report paths:",
            *[f"  - {p} (exists={os.path.exists(p)})" for p in CANDIDATE_REPORT_PATHS],
        ])
    )

    # Show training report if it exists
    if file_ready(REPORT_PATH):
        st.markdown("### Latest training report")
        with open(REPORT_PATH, "r", encoding="utf-8") as f:
            st.markdown(f.read())

    st.markdown("### Fix / Verify")
    st.markdown(
        "- Run the workflow: **GitHub → Actions → Automated ML Training Pipeline → Run workflow**\n"
        "- Confirm the repo contains a **non-empty** `models/sentiment_model.joblib`\n"
        "- Streamlit redeploys automatically after the commit\n"
    )

    st.stop()

# ---------- UI ----------
st.set_page_config(page_title="Live Sentiment Analysis Demo", layout="centered")
st.title("Live Sentiment Analysis Demo")
st.markdown(
    """
This app serves a sentiment model trained in a GitHub Actions pipeline.
Paste any text (movie review, tweet, product feedback, etc.) and get an instant prediction.
"""
)

# ---------- Guard: model must exist AND be non-empty ----------
if not file_ready(MODEL_PATH):
    render_model_not_ready()

# ---------- Load model ----------
try:
    vectorizer, model = load_model_cached(MODEL_PATH)
except Exception as e:
    st.error("Model file exists but could not be loaded (corrupt or incomplete).")
    st.write("Resolved model path:", MODEL_PATH)
    st.code(str(e))
    st.stop()

# ---------- Input ----------
user_text = st.text_area(
    "Enter text to analyze:",
    height=120,
    placeholder="This movie was absolutely fantastic! Loved every minute."
)

# ---------- Predict ----------
if st.button("Predict Sentiment"):
    if user_text.strip():
        with st.spinner("Analyzing..."):
            text_vec = vectorizer.transform([user_text])
            prediction = int(model.predict(text_vec)[0])
            prob = model.predict_proba(text_vec)[0]

            label = "Positive 😊" if prediction == 1 else "Negative 😔"
            confidence = float(max(prob)) * 100

            st.subheader(f"Prediction: **{label}**")
            st.metric("Confidence", f"{confidence:.1f}%")

            if prediction == 1:
                st.success("Positive sentiment detected!")
            else:
                st.warning("Negative sentiment detected.")
    else:
        st.warning("Please enter some text to analyze!")

# ---------- Footer ----------
st.markdown("---")
st.caption(
    "scikit-learn Logistic Regression + TF-IDF | "
    "IMDb subset training | "
    "CI-trained via GitHub Actions and deployed via Streamlit"
)
