import os
import joblib
import streamlit as st

MODEL_PATH = os.path.join("models", "sentiment_model.joblib")
REPORT_PATH = os.path.join("models", "training_report.md")

def model_ready(path: str) -> bool:
    """Model must exist and be non-empty (Streamlit currently has a 0-byte placeholder)."""
    return os.path.exists(path) and os.path.getsize(path) > 0

@st.cache_resource(show_spinner=False)
def load_model_cached(path: str):
    """Load model + vectorizer once per app session."""
    return joblib.load(path)  # returns (vectorizer, model)

def render_model_not_ready():
    st.error(
        "Model file is missing or empty.\n\n"
        "This Streamlit app expects `models/sentiment_model.joblib` to be generated by the GitHub Actions training pipeline "
        "and committed back into the repo."
    )

    # Show training report if it exists (nice portfolio touch)
    if os.path.exists(REPORT_PATH) and os.path.getsize(REPORT_PATH) > 0:
        st.markdown("### Latest training report")
        with open(REPORT_PATH, "r", encoding="utf-8") as f:
            st.markdown(f.read())

    st.markdown("### Fix / Verify")
    st.markdown(
        "- Run the workflow manually: **GitHub → Actions → Automated ML Training Pipeline → Run workflow**\n"
        "- Confirm the repo contains a **non-empty** `models/sentiment_model.joblib` after the run completes\n"
        "- Streamlit will redeploy automatically after the commit\n"
    )

    # Replace with your repo URL if you want (optional)
    st.markdown("If you’re viewing this as a portfolio reviewer, check the repository **Actions** tab for the training run logs.")

    st.stop()

# Page title and description
st.set_page_config(page_title="Live Sentiment Analysis Demo", layout="centered")
st.title("Live Sentiment Analysis Demo")
st.markdown(
    """
This app serves a sentiment model trained in a GitHub Actions pipeline.
Paste any text (movie review, tweet, product feedback, etc.) and get an instant prediction.
"""
)

# Guard: model must exist AND be non-empty
if not model_ready(MODEL_PATH):
    render_model_not_ready()

# Load the model (cached)
try:
    vectorizer, model = load_model_cached(MODEL_PATH)
except Exception as e:
    # Handles corrupted/partial joblib files too
    st.error("Model file exists but could not be loaded (corrupt or incomplete).")
    st.code(str(e))
    st.stop()

# User input
user_text = st.text_area(
    "Enter text to analyze:",
    height=120,
    placeholder="This movie was absolutely fantastic! Loved every minute."
)

# Prediction button
if st.button("Predict Sentiment"):
    if user_text.strip():
        with st.spinner("Analyzing..."):
            text_vec = vectorizer.transform([user_text])

            prediction = int(model.predict(text_vec)[0])
            prob = model.predict_proba(text_vec)[0]

            label = "Positive 😊" if prediction == 1 else "Negative 😔"
            confidence = float(max(prob)) * 100

            st.subheader(f"Prediction: **{label}**")
            st.metric("Confidence", f"{confidence:.1f}%")

            if prediction == 1:
                st.success("Positive sentiment detected!")
            else:
                st.warning("Negative sentiment detected.")
    else:
        st.warning("Please enter some text to analyze!")

# Footer
st.markdown("---")
st.caption(
    "scikit-learn Logistic Regression + TF-IDF | "
    "IMDb subset training | "
    "CI-trained via GitHub Actions and deployed via Streamlit"
)
